---
deployment:
  tasks:
    - export DEPLOYPATH=$HOME/leads.solutionscience.co.ke
    - /bin/mkdir -p $DEPLOYPATH
    - /bin/cp -R api $DEPLOYPATH
    - /bin/cp -R app $DEPLOYPATH
    - /bin/cp -R data $DEPLOYPATH
    - /bin/cp -R database $DEPLOYPATH
    - /bin/cp -R public $DEPLOYPATH
    - /bin/cp index.php $DEPLOYPATH
    - /bin/cp .htaccess $DEPLOYPATH
    - if [ ! -f $DEPLOYPATH/.env ]; then /bin/cp .env.production.example $DEPLOYPATH/.env.example; fi
